version: '3.7'

services:

  postgres:
    image: 'postgres:12.1-alpine'
    
    env_file:
      - '.env'
    
    ports:
      - '$PG_PORT:5432'
    
    volumes:
      - postgres:/var/lib/postgresql/data
    
    networks:
      backend:
        aliases:
          - postgres

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    
    logging:
      driver: none 
    
    env_file:
      - '.env'
    
    ports:
      - '$PGADMIN_PORT:80'
    
    volumes:
      - pgadmin:/var/lib/pgadmin
    
    depends_on:
      - postgres
    
    networks:
      backend:
        aliases:
          - pgadmin

  webinterface:
    build: ./trader
    
    ports:
      - '$WEBINTERFACE_PORT:8000'
    
    env_file:
      - '.env'
    
    depends_on:
      - postgres
    
    networks:
      backend:
        aliases:
          - webinterface_backend
          
  binancedatahandler:
    build: ./binancedatahandler
    
    env_file:
      - '.env'
    
    depends_on:
      - postgres
      - trader
    
    networks:
      backend:
        aliases:
          - binancedatahandler_backend

networks:
  backend:
    driver: bridge
  
volumes:
  postgres:
    driver: local
    name: postgres
  
  pgadmin:
    driver: local
    name: pgadmin