version: '3.7'

services:

  postgres:
    image: 'postgres:12-alpine'
    
    env_file:
      - '.env'
    
    ports:
      - '$PG_PORT:5432'
    
    volumes:
      - postgres:/var/lib/postgresql/data
    
    networks:
      backend:
        aliases:
          - postgres

  pgadmin:
    image: dpage/pgadmin4
    
    env_file:
      - '.env'
    
    ports:
      - '$PGADMIN_PORT:80'
    
    volumes:
      - pgadmin:/var/lib/pgadmin
    
    depends_on:
      - postgres
    
    networks:
      backend:
        aliases:
          - pgadmin

  trader:
    build: ./trader
    
    ports:
      - '$TRADER_PORT:8000'
    
    env_file:
      - '.env'
    
    depends_on:
      - postgres
    
    networks:
      backend:
        aliases:
          - trader_backend
          
  binancedatahandler:
    build: ./binancedatahandler
    
    ports:
      - '$BINANCE_HANDLER_PORT:80'
    
    env_file:
      - '.env'
    
    depends_on:
      - postgres
      - trader
    
    networks:
      backend:
        aliases:
          - binancedatahandler_backend

networks:
  backend:
    driver: bridge
  
volumes:
  postgres:
    driver: local
    name: postgres
  
  pgadmin:
    driver: local
    name: pgadmin